apiVersion: v1
kind: Service
metadata:
  name: commotrade-service
spec:
  type: LoadBalancer # This gives us a Public IP
  selector:
    app: commotrade
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: 8000